qjebbs/vscode-plantuml

package.json
src/config.ts
src/httpExporter.ts

Hey qjebbs,
your commit https://github.com/qjebbs/vscode-plantuml/commit/1043bb159be13e9ec570b5b8b863d1fd21e43de2 unfortunately broke the httpExporter Logic as well. I updated the code accordingly.
You can test it against http://plantuml.rado0x54.com:
```
"plantuml.urlServer": "http://plantuml.rado0x54.com",
"plantuml.previewFromUrlServer": true,
"plantuml.urlServerIndexParameter": "idx"
```
e.g.
http://plantuml.rado0x54.com/png/IzIrIx9Io4ZDoSctvifBBIz8J4zLWD8bcIKvgLn9kdQ92bOAIOd9sGhvUI0v1P2aDG00?idx=0
&
http://plantuml.rado0x54.com/png/IzIrIx9Io4ZDoSctvifBBIz8J4zLWD8bcIKvgLn9kdQ92bOAIOd9sGhvUI0v1P2aDG00?idx=1
Quick release would be appreciated.

Fixed httpExporter for multipage diagrams

---

package.json
syntaxes/codeblock.json

This is to add support of the syntax highlighting in the editor in markdown files.
This is inspired from https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example
Tested successfully, example:

add plantuml syntax highlighting in markdown fenced block (in editor)

---

src/plantuml/formatRules.ts

hey @qjebbs been using your extension quite a lot in the past weeks. it's **great**. i was wondering though why block formatting for **opt** sequence groups is missing? 
**opt** keyword is mentioned on plantuml sequence diagram documentation http://plantuml.com/sequence-diagram
So i added **opt** keyword to the block formatting rules for the other sequence groups. 😃

Feat: format opt sequence group blocks

---

syntaxes/diagram.yaml-tmLanguage

The !ifndef preprocessor directive is missing from the syntax highlighting definition and thus not highlighted. This PR fixes that.

Add !ifndef to preprocessor syntax highlighting

---

package.json
src/plantuml/config.ts

Related to issue #175
Plantuml in markdown preview only works, when Preview Security Settings are set to "Allow insecure content". When setting plantuml.render to HTTPS instead of HTTP, plantuml preview also works with Strict Security Settings.
This pull request updates the default render settings to HTTPS instead of HTTP.

Use https instead of http for default online render server url.

---

includes/styles/blue.wsd

The diamond used for branches in activity diagram now uses the same style as the other elements.

update blue style - add coherence to activity diagram

---

package.json

Set scope to machine-overridable to support setting the values within the workspace settings.

set scope config scope to machine-overridable, solves #263

---

syntaxes/diagram.yaml-tmLanguage

For example, recognize the field `activé` in a class:
class A {
activé : Boolean
}

Support syntax highlighting of functions and fields with accents

---

snippets/sequence.json
syntaxes/diagram.yaml-tmLanguage

Hi.
Recent PlantUML sequence diagrams have an additional "return" keyword.
e.g.
```
@startuml
Bob -> Alice : hello
activate Alice
Alice -> Alice : some action
return bye
@enduml
```
I added initial support for the "return" keyword.

Initial support for "return" keyword

---

package-lock.json
package.json

Fixes #305 
Toggle comments now work in markdown code fences.
NOTE: Running `npm install` automatically bumped the package version. I'm guessing for some reason this might have been forgotten in the last commit or this is a side effect of the publish release process.

Ensure comment toggles work in markdown

---

src/plantuml/diagram/include.ts

When the `diagram` was created with the content-only constructor, the document information is missing, and therefore `diagram.parentUri` property is `undefined`. A check is necessary before accessing the `.fsPath` property.

Check before using the `parentUri.fsPath` property

---

src/plantuml/diagram/include.ts

Remove the `@start...` and `@end...` tags from an included file before adding it to the parent.
The code removes the first line, which starts (ignoring whitespaces) with `@start`.
Then it removes the last line, which starts (ignoring whitespaces) with `@end`.
Both operations remove exactly one new-line (either single `\n` or `\r\n`), so that there is no empty line but the line before and the line after don't get merged.
Fixes #298

Fix the include preprocessor creating nested diagrams

---

src/plantuml/sourceExtracter/extractSource.ts

without them, encoding settings would not be taken into account
{
"plantuml.commandArgs": [
"-Dfile.encoding=UTF-8"
],
"plantuml.jarArgs": [
"-charset UTF-8"
]
}
Fixes: #383

Add commandArgs and jarArgs to the sourceExtracter

---

src/plantuml/diagram/include.ts

Adds a check to see if path being included exists and is a file before tyring to read
Fixes #411

Fix #411 - Error in console while typing include

---

syntaxes/plantuml.yaml-tmLanguage

Modification of `plantuml.yaml-tmLanguage` in order to manage full online block comment on syntax highlighting (See #418).
Example to be corrected:
1. Example on component/deployment diagram
```puml
@startuml
' Simple online comment
/' this is a block comment
/' until this '/
[c1]
[c2] /' block comment '/
/' block comment '/ [c3]
node n #palegreen /' block comment '/ 
@enduml
```
2. Example on sequence diagram
```puml
@startuml
/' comment '/ a->b
a->b /' comment always KO '/
autonumber 11 /' 11 '/
a<-b /' comment always KO '/
/' 13 '/ autonumber 13 
/' comment '/ a->b
@enduml
```
**Restriction**
:warning: This PR fixes the first example; but not all for the second where some syntax highlighting errors remain (see` /' comment always KO '/`)
:sos: Requesting assistance to complete the PR: …

syntax highlighting: manage full online block comment

---

syntaxes/plantuml.yaml-tmLanguage

Improve syntax highlighting for preprocessing keyword (VSCode vs GitHub), with change the scope of the preprocessing keywords:
- from `support.class.preprocessings.source.wsd`
- to `entity.name.function.preprocessings.source.wsd`
Related issues:
- Fixes qjebbs/vscode-plantuml#428
- Fixes github/linguist#5530
Ref. and intersection of:
- https://github.com/microsoft/vscode/tree/main/extensions/theme-defaults/themes
- https://github.com/primer/github-syntax-light
- https://github.com/primer/github-syntax-dark

fix: syntax highlighting: change the scope of the preprocessing keywords (VSCode vs GitHub)

---

README.md

The [`adoptopenjdk` brew cask is deprecated and no-longer updated since 2021-08-01](https://github.com/AdoptOpenJDK/homebrew-openjdk/blob/f6e8c971c98f5ba48aedf2a5d218ebc914ee2304/README.md#L1,L2).
The [`adoptopenjdk` team recommend switching to the, homebrew maintained, temurin cask instead](https://github.com/AdoptOpenJDK/homebrew-openjdk#-deprecation-notice-).
This PR is a small documentation update to reflect the new recommendation

docs: fix AdoptOpenJDK deprecation: use temurin

---

templates/js/zoom.js
templates/preview.html

Because the built-in copy operation on the page is not available, a button for copying images has been added to facilitate sharing pictures without saving them locally. It may not conform to previous code styles. Please understand.

add btn for copy preview image to clipboard.

---

README.md

Added infopoint to point to the PlantUML builtin webserver, that can be run directly and works nicely with this plugin.

README.md: Added note on builtin picowebserver

---

syntaxes/plantuml.yaml-tmLanguage

To continue #425, #452 and #454:
Mod:
- Add `goto` keyword (on `line begin keywords`)
- Add [timing's](https://plantuml.com/en/timing-diagram) keyword (on `line begin keywords`):
- binary
- clock
- concise
- robust

mod: syntax highlighting: Improve syntax highlighting - Add some keywords

---

src/plantuml/renders/plantumlServer.ts

Not falling back to using GET requests to a server in case an initial POST request to the same server was successful. The GET method will be picked only in case the first POST call was failed for any reason.
[Issue](https://github.com/qjebbs/vscode-plantuml/issues/396)

[Fix] Getting "Error: 414 URI Too Long" until restart of vscode

---

CHANGELOG.md

Fix some typo and add some ref on `ChangeLog`:
- add some `)`
- add some ref to 'Update syntax highlighting'
- add newline for §2.15.1

upd: fix some typo and add some ref on `ChangeLog`

---

syntaxes/plantuml.yaml-tmLanguage

To continue #425, #452, #454 and #457:
Add on `hide & show` section:
- `remove` 
- `empty description`
- `@unlinked`
- `$tag`
Add on `line begin keywords`:
- `json`
- `compact`

mod: syntax highlighting: Improve syntax highlighting - Add some keywords (`remove`, `compact`, ...)

---

package.json
src/plantuml/renders/httpWrapper.ts
src/plantuml/renders/local.ts
src/providers/previewer.ts

If a process exits (either normally or due to an error) before the call to `process.kill('SIGINT')` inside function `killTask`, then the signal cannot be delivered to the process, and the handler registered on 'exit' event for the process won't be executed, thus leaving the promise unresolved, and therefore the extension gets stuck.
To solve this, check the value returned by `process.kill('SIGINT')`:
- If that's `true`, then the signal is delivered, and the 'exit' event handler should be executed;
- If that 's `false`, then the signal cannot be delivered. Then, check the `exitCode` of the process. If that is not `null`, then the process already exited, therefore there is nothing more to do than resolve the returned promise.
Note that **theoretically**, in case the call to …

Fix child processes killing function

---

package.json

similar to markdown, rst and other extentions, we now also show the $(open-preview) icon on PlantUML files. This is much more inline with generall vscode behavior and should help users to seamlessly change between extentions
Looks like this:
closes #431

add preview button to PlantUML files

---

src/plantuml/formatRules.ts
syntaxes/plantuml.yaml-tmLanguage

I am aware the formatter is deprecated, but it is nevertheless very useful to me.
I was missing the handling of the switch statement, so here it is.

 Rules for syntax highlighting  and formatting of switch statements in activity diagrams
